hrd/hrd/catalog-console.xml

ref https://github.com/colorer/FarColorer/issues/7 sort list a bit

ref https://github.com/colorer/FarColorer/issues/7 sort list a bit

---

hrc/hrc/base/lua.hrc

The issue was reported on the far manager forum http://forum.farmanager.com/viewtopic.php?p=129135#p129135. This patch is the more correct fix for the issue.

hrc_lua: "if then end" colorizing fixed

---

hrc/hrc/base/lua.hrc

Added LuaJIT support: bitwise operation, ffi cdef c-code highlighting (import cpp scheme).
Other minor changes.

LuaJIT: bitwise operation, ffi cdef

---

hrc/hrc/scripts/powershell.hrc

Added support for PowerShell v5 (enum, class) and v4 (configuration).

powershell.hrc - added enum and partially class and configuration

---

hrc/hrc/scripts/powershell.hrc

More impovements for PowerShell v5

powershell.hrc - improved class schemes, revised standard cmdlets

---

hrc/hrc/base/fsharp.hrc
hrc/hrc/proto.hrc
hrc/hrc/scripts/powershell.hrc
hrd/hrd/console/contrib/visual.hrd

- fsharp.hrc: Treat variables and functions as values.
- powershell.hrc: Remove artificial support of output regions.
- visual.hrd: Remove proposed but not accepted features for Colorer.

fsharp.hrc, powershell.hrc, visual.hrd

---

hrc/hrc/base/groovy.hrc
hrc/hrc/inet/gsp.hrc
hrc/hrc/proto.hrc
hrc/test/_valid/groovy/LearnGroovy.groovy.html
hrc/test/groovy/LearnGroovy.groovy

This is based on http://yury-finkel.livejournal.com/201075.html
I've added test file and output.

Add Groovy support.

---

catalog.xml_

Restore a missing link to user-defined color schemes.

Restore link to hrd/catalog-user.xml

---

hrc/hrc/base/perl-keywords.ent.hrc

To cover the issue #83 partially:
> ну и пора бы добавить всякие там say и чего там нового за это время накопилось

add coloring Perl v.5.10+ features

---

hrc/hrc/inet/graphql.hrc

- Treat descriptions and string literals separately.
- Amend parsing numbers, add dot errors.

Improve graphql.hrc

---

hrc/hrc/base/fsharp.hrc

- support F# 5 interpolated strings
- support octal and bit numbers
- support underscore in numbers
- support shebang

Improve fsharp.hrc

---

hrc/hrc/proto.hrc

> Groovy build script (`.gradle`)
https://docs.gradle.org/current/userguide/writing_build_scripts.html#sec:the_script_api

proto.hrc: .gradle scripts are Groovy

---

hrc/hrc/base/fsharp.hrc
hrc/hrc/scripts/powershell.hrc

- fsharp.hrc
- support Unicode names
- powershell.hrc
- add `split` to regex operators
- add missing automatic variables

Update fsharp.hrc and powershell.hrc

---

hrc/hrc/base/cpp.hrc

In the given commit I've copied all the keywords from the https://en.cppreference.com/w/cpp/keyword so the list of C++ keywords is fully complete.

C++20 update

---

hrc/hrc/scripts/shell-bash.hrc
hrc/hrc/scripts/shell-posix.hrc

Resolves:
* chpock/ck.colorer-schemes#1
* chpock/ck.colorer-schemes#3
* chpock/ck.colorer-schemes#4

Fix minor shell/bash issues

---

hrc/hrc/misc/markdown.hrc

markdown.hrc - use markdown2 for user extensions

---

hrc/hrc/misc/markdown.hrc

Fix #149, 3 more similar cases.

markdown.hrc - amend emphasis with underscores

---

CHANGELOG.md
hrc/hrc/scripts/shell-bash.hrc

Closes: colorer/Colorer-schemes#172

[shell-bash] fix indirect expansion+transformation

---

hrc/hrc/base/c.hrc

C: format string length modifiers since C99

---

hrc/hrc/scripts/powershell.hrc

Add to outlined: `#requires` and top level `process|begin|end|dynamicparam|clean` blocks.

powershell.hrc - add some outlined

---

base/hrd/catalog-rgb.xml
base/hrd/rgb/violet.hrd

Added another color theme for editor
