- hrc/hrc/base/python.hrc
This prevents non-functioning escapes inside of raw strings from being highlighted
> python.hrc: Handle raw strings separately

- hrc/hrc/scripts/sh.hrc
- descriptive comments added
- process substitution <() and >() highlighted similar to subprocess execution $()
- attempt to return shebang coloring
> hrc/sh.hrc: process redirection and few descriptive comments

- hrc/hrc/scripts/batch.hrc
heredoc is well-known way to embed milti-line strings within code of shell, perl and others. Batch scripts do not have such a kind the feature. The following links provide attempt to implement heredoc in batch scripts:
http://stackoverflow.com/a/29329912/3627676
http://forum.script-coding.com/viewtopic.php?id=10536
These changes to batch.hrc allow to highlight the specially marked strings as heredoc, so the text within the markers is colorized as simple text.
> hrc_batch: heredoc highlighting

- hrc/hrc/proto.hrc
Scripts like Godot's SCsub which can start with plain import and/or """
D language is less popular and have imports terminated with semicolon
> proto.hrc: Improve Python detection

- hrc/hrc/proto.hrc
- hrc/hrc/rare/haskell.hrc
I have created this color file for the Haskell language.
It is very useful and covers at least the common parts of the language.
Features:
* Line comments
* Block comments
* Pragmas
* Keywords
* Keywords for import statements only (such as "as" and "qualified")
* Strings (Copied from OCaml)
* Brackets
* Highlight types and constructors based on initial upper case letter
* Outline for function, type, class etc. declaration (based somewhat on code conventions instead of on syntax, but still)
Haskell support for Eclipse is otherwise pretty lacking. The EclipseFP plugin is still a bit shaky. Colorer might fill a gap here.
I used the Ocaml file as a starting point.
> Add Haskell color file

- hrc/hrc/scripts/sh.hrc
The following forms are supported now:
1. The minus sign allows indenting here documents in shell scripts
<<   HEREDOC
<<-  HEREDOC
2. The single quotes around the label disable the interpolating of heredoc
<<  'HEREDOC'
<<- 'HEREDOC'
> Add support for single-quoted heredocs

- hrc/hrc/base/fsharp.hrc
- Use derived regions instead of default.
- Treat false, true, null as constants.
- Review F# identifier patterns.
- Improve outlined items.
> Improved fsharp.hrc

- hrc/hrc/inet/jscript.hrc
A small improvement to jscript scheme that allows to colorize javascript labels independently of the number of whitespaces at the beginning of the labels.
> Hrc jscript

- build.sh
Use absolute paths.
Added quoting to shield against unsafe characters in CLASSPATH and parameters.
> Fix fragile buildscript

- hrc/hrc/proto.hrc
New MSBuild project files do not have traditional XML declaration. As a result,
they are not recognised as XML files because .*proj is not in the XML pattern.
It looks like the pattern .*proj does not conflict with other types.
> Treat .*proj files as XML.

- hrc/hrc/proto.hrc
colorize profile setting files in the same way as to regular shell scripts.
Supportable shells:
bash/ksh/zsh
Supportable files:
.bashrc
.kshrc
.zshrc
.bash_profile
.profile
.zprofile
> colorize bash/ksh/zsh profile setting files

- hrc/hrc/misc/markdown.hrc
- support fenced code blocks with language names
- replace indentation tabs with spaces
- support end double spaces in quotes
> markdown.hrc - support fenced code blocks with language names

- hrc/hrc/inet/jscript.hrc
Syntax highlighting for ES2015 template strings as per https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals
> Template literal support for jScript

- hrc/hrc/base/nix.hrc
This form of escape sequence was missing
https://github.com/NixOS/nix/blob/6a5bf9b1438ed0b721657568fbb3a7c0b829e89e/src/libexpr/lexer.l#L186-L187
> nix.hrc: add missing blockstring escaping

- hrc/hrc/base/cpp.hrc
C++11 allowed curly brackets in expressions inside round brackets where
they were not allowed before:
* Lambda functions: ([](){ return 1; })();
* List initialization: vector({1, 2, 3})
This patch adds {} as correct pair inside 'Expression' region,
hence they are not highlighted as errors anymore.
Fixes #78
> cpp.hrc: allow curly brackets inside expressions, fixes #78

- hrc/hrc/proto.hrc
for example: "script.svgo.js" detected as svg
> fix wrong svg extension

- hrc/hrc/scripts/sh-keywords.ent.hrc
- hrc/hrc/scripts/sh.hrc
Highlight the most frequently used commands:
- sed (it is already declared)
- awk
- grep
- find
- xargs
- wc
- sort
- uniq
Simplify "grep" highlighting:
- no special coloring for something similar to "grep -q".
> highlight the most frequestly used unix commands simplify "grep" highlighting

- hrc/hrc/proto.hrc
As far as I can see `.ts` is not used, so there should be no conflicts introduced.
TypeScript is a super set of JavaScript, so that this association works quite well.
In any case it is much better than C++ currently selected due to similar header comments.
> Associate .ts files (TypeScript) with JavaScript in proto.hrc.

- hrc/hrc/proto.hrc
Повысить приоритет расцветки `main\perl` вместо `rare/Sicstus Prolog` для файлов `.pl`.
Файлы `.pl` подсвечиваются как `rare/Sicstus Prolog`, если в первой строке не указан шебанг. Возможны три варианта:
* или только для perl: `<filename weight="3">/\.(pl[sx]?|pm|pod|t|ph)$/i</filename>`
* или только для Sicstus Prolog: `<filename weight="1">/\.pl$/i</filename>`
* или оба варианта сразу
> set perl higher priority versus rare sicstusProlog

- hrc/hrc/proto.hrc
Jad is old-fashioned and sometimes not able to correctly decompile class files. 
CFR is another java decompiler supporting modern Java features. It lives at https://github.com/leibnitz27/cfr. It decompiles class files prepending the following minimal header (version is optional):
```
/*
* Decompiled with CFR 0.150.
*/
```
It could be reasonable to support CFR output.
> support CFR, another java decompiler

- hrc/hrc/proto.hrc
https://editorconfig.org
These files are used by many modern text editors and their plugins.
> Associate .editorconfig files with "config" in proto.hrc.

- hrc/hrc/base/go.hrc
`func` is the special and important keyword which deserves this special treatment.
After all, Colorer designed and provided the special def:FunctionKeyword.
Making `func` also Outlined is useful for "Colorer/Outliner list".
Trimmed some trailing spaces as well.
> go.hrc - treat func as FunctionKeyword and Outlined

- hrc/hrc/base/csharp.hrc
- hrc/hrc/proto.hrc
Moved recently added `graphql.hrc` to other `inet` group declarations in the prototype file.
Otherwise GraphQL is shown in its own separate `inet` group with just one item in it.
Added new keywords `async` and `await`, frequently used nowadays.
Technically they are context dependent, i.e. in some cases they may be used as names.
To define their proper context parsing is tricky, C# schema is rather minimalistic.
For the sake of keeping its simplicity, I suggest just using keywords.
(I'll improve this later if there are drawbacks/complains).
These changes do not affect result colors.
They fix the outline list which was not quite right for many years.
**Return value type**
Replaced
(\w [\w*\[\]\s]+? [*\[\]\s])
with
(\w [\w*\[\]\s.<,>]*? [*\[\]\s])
- added `.` because full type names with …
> Update csharp.hrc and amend graphql.hrc prototype.

- hrc/hrc/db/sql.hrc
- hrc/hrc/scripts/iss.hrc
Added support syntax InnoSetup 6.1.2 (based on IS documentation).
Added new keywords `foreach`, `datetime`, `elif`, `hold`, `serial`, `smallfloat`, `let`, `unload`.
Added `{ }` for comments.
Added `foreach` and `while` loop processing.
Added `begin work` and `commit work` as pairs for block to be commited.
> Update sql.hrc and iss.hrc

- hrc/hrc/base/csharp.hrc
- Support interpolated and interpolated verbatim strings.
- Support character and string escaping per C# specs.
- Tweak `#region` and `yield`.
- Support `partial` keyword.
- Use 2 space indentation.
- Use `def:` explicitly.
> Improve csharp.hrc

- hrc/hrc/base/nix.hrc
A bit unexpected but ~ has to be escaped as \~ in colorer regex
Nix highlighter did not highlight home-base paths like `~/foo/bar.nix`
> ~ has to be escaped as \~ in colorer regex

- hrc/hrc/scripts/awk.hrc
reported at https://forum.farmanager.com/viewtopic.php?p=165951#p165951
> Для awk он не понимает конструкцию $(i) - подсвечивает $( красным и выводит в ошибках. 1.3.0.23
solution:
-- add a new scheme awkComplexArg (inherited from awk)
-- apply the new scheme for the block $( ... )
> awk: solve the issue with $( ... )

- hrc/hrc/proto.hrc
CSharp scripts usually have .csx extension.
> Add .csx extension to csharp schema in proto.hrc

- hrc/hrc/lib/regexp.hrc
PCRE specs:
- [NAMED CAPTURE GROUPS](https://www.pcre.org/current/doc/html/pcre2pattern.html#SEC16)
- [BACKREFERENCES](https://www.pcre.org/current/doc/html/pcre2pattern.html#backreferences)
According to the specs, at least these two forms are supported:
```
(?<name>bar) \k<name>
(?'name'bar) \k'name'
```
Currently, the scheme does not recognise named capture groups and treats named backreferences as syntax errors.
<https://regex101.com/> shows that both forms are valid in PCRE2 (PHP >= 7.3.) and PCRE (PHP <7.3).
The commit adds these two forms support to the schema `pcre.base`.
The region `SpecOperator` is chosen to match regions of backreferences (`\1`, etc.).
Colorer results before and after the change (with `visual.hrd` and `powershell` scheme with inherited `regex` scheme):
form 1 …
> regex.hrc/pcre.base: support named capture groups and backreferences

- hrc/hrc/scripts/far/farmenu.hrc
Color commands with prefixes `lua:` using `lua` scheme, `ps:` and `vps:` using `powershell` scheme.
> farmenu.hrc - color well known lua and powershell plugin commands

- hrc/hrc/base/c.hrc
Closes #104 
String literal syntax is described here:
https://en.cppreference.com/w/cpp/language/string_literal
Not sure it is done the best way (probably "RawStringContent" scheme is not needed at all), but it works
> Add support for C++11 string literals

- hrc/hrc/base/csharp.hrc
Interpolated raw strings are treated the same as not interpolated. For now it's rather important to fix broken syntax with used `"""`.
> csharp.hrc - support C# 11 raw strings

- hrc/hrc/proto.hrc
Added <firstline> regex for JSON, HTML, CSS and SQL. Tested a fair bit, eg with similar languages like generic XML to hopefully avoid collisions. Also set some weights which I think may be right. Currently in-use on tohtml.com
**CSS**: This pattern aims to catch lines starting with optional whitespace, followed by a selector (class ., ID #, or element/tag name), and then an opening brace {.
**JSON**: This pattern matches a JSON object's start, specifically looking for a key defined by double quotes and followed by a colon.
**SQL**: These patterns aim to match common SQL keywords, statements and comments .
**HTML**: These patterns identify HTML through common opening tags, else lines that start with HTML-specific tags.
> Added firstline regex for HTML, CSS, SQL and JSON

- CHANGELOG.md
- hrc/hrc/scripts/shell-bash.hrc
Closes chpock/ck.colorer-schemes#5
> Fix backticks in for loop in bash scheme

- hrc/hrc/proto.hrc
`.xaml` is the standard extension for XAML files used in .NET for WPF and UWP applications.
It's XML and should be recognized as XML, so I add this extension to "xml" prototype.
Without this change "smarty" incorrectly takes over due to its rather too broad `firstline` definition
```xml
<prototype name="smarty" group="inet" description="Smarty PHP Templates">
<location link="inet/smarty.hrc" />
<filename>/\.smarty$/</filename>
<filename>/\.tpl$/</filename>
<firstline>/^\s*[\{&lt;]/x</firstline>
</prototype>
```
> Add *.xaml to xml prototype.

- hrc/hrc/misc/markdown.hrc
* `<% %>` marks Obsidian Templater blocks.
> markdown.hrc - add Obsidian Templater blocks

- hrc/hrc/scripts/far/farmenu.hrc
- Add optional `@` before Lua and PowerShellFar prefixes
- Support `luas:` in addition to `lua:`
> farmenu.hrc - amend Lua and PowerShellFar
